# Mapeamento imagem -> LaTeX nativo (núcleo matemático, sem cifrões).
# Fontes: 4 agentes de transcrição (linhas/seções verificadas no plano-v2.tex)
# + conferência visual do autor em: 97, 132, 145, 152, 179, 198, 211 (=j/n/m/t ok).
# Ajustes manuais: image145=n, image132=j, image179=m_t (glifos verificados).
MAP = {
# --- 1.1.1 aleatório (ER) ---
"image175.gif": r"G(N,K)",
"image142.png": r"K",
"image126.png": r"N",
"image157.gif": r"\binom{M}{K}",
"image47.png": r"M = N \times (N-1)/2",
"image215.png": r"0 \le K \le M",
"image24.png": r"G(N,p)",
"image158.png": r"p",
"image40.gif": r"M = N \times (N-1)/2",
"image74.png": r"(i,j)",
"image21.png": r"1-p",
"image121.png": r"P(G) = p^{K} \times (1-p)^{(M-K)}",
"image137.png": r"P(K) = \binom{M}{K} \times p^{K} \times (1-p)^{(M-K)}",
"image19.png": r"\langle k \rangle",
"image42.png": r"\langle k \rangle < 1",
"image148.gif": r"\ln(N)",
"image63.png": r"\langle k \rangle = 1",
"image205.png": r"N^{2/3}",
"image206.png": r"\langle k \rangle > 1",
"image71.png": r"S",
"image173.gif": r"S = 1 - e^{-zS}",
"image187.gif": r"z = \langle k \rangle",
"image10.gif": r"S > 0",
"image143.gif": r"\langle k \rangle > 1",
"image197.gif": r"\langle k \rangle_{c} = 1",
# --- 1.1.2 pequeno mundo (WS) ---
"image136.png": r"n",
"image198.png": r"k",
"image35.png": r"0 < p < 1",
"image32.png": r"L(p)",
"image72.png": r"C(p)",
"image61.png": r"v",
"image23.png": r"k_{v}",
"image30.png": r"k_{v}(k_{v}-1)/2",
"image182.png": r"C_{v}",
# --- 1.1.3 livre de escala ---
"image116.png": r"P(k) \sim k^{-\gamma}",
"image200.png": r"\gamma",
"image172.gif": r"f(k)",
"image128.png": r"f(ck) = g(c)\,f(k)",
# --- 2.1.1 Price / 2.1.2 BA ---
"image103.png": r"c",
"image152.png": r"m",
"image203.png": r"m_{0}",
"image77.gif": r"m_{0}",
"image52.png": r"t",
"image145.png": r"n",
"image16.png": r"m \le m_{0}",
"image123.gif": r"m \le m_{0}",
"image132.png": r"j",
"image97.png": r"\Pi(k_{i}) = k_{i} / \sum_{j} k_{j}",
"image13.png": r"t + m_{0}",
"image179.gif": r"m_{t}",
"image125.png": r"\gamma \approx 3",
"image211.png": r"k_{i}(t) = m\left(\frac{t}{t_{i}}\right)^{1/2}",
"image83.png": r"P(k) \sim k^{-3}",
"image33.png": r"\beta = 1/2",
"image208.png": r"\Pi(k) \sim k",
"image169.png": r"\Pi(k) \sim k^{\alpha}",
"image186.png": r"\alpha = 1",
"image78.png": r"\alpha \neq 1",
"image124.gif": r"\alpha < 1",
"image92.png": r"P(k)",
"image135.gif": r"\alpha > 1",
"image212.png": r"\alpha",
# --- 2.1.3 Bianconi-Barabási ---
"image184.png": r"\eta",
"image26.png": r"\rho(\eta)",
"image64.png": r"\Pi(i) = \frac{\eta_{i}k_{i}}{\sum_{j}\,\eta_{j}k_{j}}",
"image104.png": r"k_{\eta}(t,t_{0}) = m\left(\frac{t}{t_{0}}\right)^{\beta(\eta)}",
"image7.png": r"\beta(\eta) = \frac{\eta}{C}",
"image176.png": r"C",
"image119.png": r"P(k) \sim \frac{k^{-(1+C^{*})}}{\ln(k)}",
"image100.png": r"(t_{0})",
"image18.png": r"\eta_{i}",
"image162.png": r"m = 2",
"image160.png": r"\eta_{j}k_{j}",
"image195.png": r"N = 10^{6}",
"image54.png": r"(\eta_{i}k_{i})",
"image110.gif": r"2 < \gamma < 3",
# --- 2.1.4 Holme-Kim ---
"image17.png": r"m_{t}",
"image105.png": r"m_{t} = 0",
"image59.gif": r"m_{t} > 0",
"image192.png": r"u",
"image180.png": r"m - 1",
"image156.gif": r"P_{t}",
"image147.png": r"m_{t} = (m-1)\times P_{t} \quad\Longrightarrow\quad P_{t} = \frac{m_{t}}{\,m-1\,}",
"image101.png": r"1 - P_{t}",
"image51.png": r"\gamma = 3",
# --- 2.2.1 D'Souza (pedágio) ---
"image146.png": r"[0,1]",
"image27.png": r"G_{t} = (V_{t}, E_{t})",
"image6.png": r"c_{t} = \min_{j}[\alpha n_{tj} + h_{j}]",
"image111.png": r"C_{t}",
"image75.png": r"\alpha > 0",
"image165.png": r"n_{tj}",
"image94.png": r"n_{tj} = |\lbrace k \in V_{t-1} \mid x_{j} < x_{k} < x_{t}\rbrace|",
"image79.png": r"h_{j}",
"image5.png": r"0",
"image151.png": r"h_{t} = h_{j}+1",
"image213.png": r"x_{t}",
"image188.png": r"x_{t} \sim U(0,1)",
"image131.gif": r"x_{j} < x_{t}",
"image88.png": r"1/\alpha",
"image216.png": r"\gamma = 2",
# --- 2.2.2 Cancho-Solé ---
"image98.png": r"d",
"image177.png": r"\rho",
"image58.png": r"D",
"image122.png": r"D = \frac{\sum_{i<j} D_{ij}}{\,n(n-1)/2\,}",
"image199.png": r"D_{ij}",
"image91.png": r"D_{l} = \frac{n+1}{3}",
"image34.png": r"d = \frac{D}{D_{l}} = \frac{3D}{n+1}",
"image89.png": r"\rho = \frac{\langle k \rangle}{\,n-1\,}",
"image57.png": r"E(\lambda) = \lambda d + (1-\lambda)\rho",
"image130.png": r"\lambda",
"image167.png": r"A = a_{ij}",
"image62.png": r"A",
"image96.png": r"n = 100",
"image141.png": r"\rho = 0.2",
"image45.png": r"a_{ij}",
"image99.png": r"1",
"image178.png": r"E(\lambda, t+1)",
"image107.png": r"E(\lambda, t)",
"image4.png": r"T",
"image159.png": r"H(p_{k}) = -\sum_{k=1}^{n-1} p_{k}\log p_{k}",
"image174.png": r"p_{k}",
"image81.png": r"\xi",
"image209.png": r"H(\lambda)",
"image31.png": r"\lambda \approx 0",
"image114.png": r"\lambda \approx 0{,}01",
"image39.png": r"P(k) \sim e^{-k/\xi}",
"image56.png": r"\lambda \approx 0{,}08",
"image25.png": r"\xi \approx 20",
"image171.png": r"0{,}25 < \lambda < 0{,}8",
"image138.png": r"\lambda \ge 0{,}8",
"image66.png": r"k = n-1",
"image113.png": r"\Gamma(\lambda) = \frac{1-d(\lambda)}{\rho(\lambda)}",
"image28.png": r"n > 100",
}
